refractionPOINT/usp-adapters

containers/general/tool.go
Fixing bug with config file handling.
=> Log conf file

cloudbuild_general.yaml, cloudbuild_release.yaml, file/client.go, wel/noop.go
Expand the adapter builds to openbsd, freebsd and netbsd.
=> Expand builds to *bsd

cloudbuild_general.yaml, cloudbuild_release.yaml
=> Fix the arch name for standard.

go.mod, go.sum, o365/client.go
Performance enhancement for Office365. Avoids a full serialization roundtrip.
=> Don't deserialize o365 to avoid cpu usage.

cloudbuild_release.yaml
=> Fix cloudbuild file for zeek.

cloudbuild_release.yaml
Fixing another bug in the cloudbuild.
=> Fixing another issue with the cloudbuild.

cloudbuild_release.yaml
=> Fix zeek build dir.

containers/zeek/Dockerfile, containers/zeek/README.md, containers/zeek/run.sh
Document the zeek container and include an env escape hatch for more zeek params.
=> Adding zeek docs and an escape hatch.

cloudbuild_release.yaml, containers/k8s_pods/Dockerfile, containers/k8s_pods/README.md, containers/k8s_pods/run.sh
Defining a new container for k8s pods.
=> K8s container

cloudbuild_release.yaml
Prod build is now OOMing. Instead of trying to serialize the builds I'll just throw hardware at it.
=> Increase build machine size.

cloudbuild_general.yaml, cloudbuild_release.yaml
Produce native builds with an older glibc compatibility.
=> Fix the builder container for glibc dep.

cloudbuild_general.yaml, cloudbuild_release.yaml, containers/connectivity/main.go
Now building a new binary (available soon at downloads.limacharlie.io) which will, given an `oid` run connectivity checks to determine if the LC cloud can be reached and if not at what stage it's failing.
It checks:
- DNS resolution
- TCP connection
- SSL connection
- SSL certificates
=> Connectivity

cloudbuild_release.yaml
=> Fix build reference.

containers/connectivity/main.go
Fix bug in the printing of the fingerprints.
=> Fix printing of the ssl fingerprint.

k8s_pods/client.go, k8s_pods/conf.go, k8s_pods/engine.go, k8s_pods/engine_test.go
=> Add support for include and exclude pods.

sqs-files/client.go
We could only resolve the bucket if it was in the root. We can now Find it deeply.
=> Allow deep get on bucket in sqs-file.

simulator/client.go
Simulator is missing a wait on close.
=> Missing simulator wait.

simulator/client.go
Make it easier to stop a simulator mid stream.
=> Support interruptible sim sleep.

sqs-files/client.go, utils/json.go, utils/json_test.go
Adding support for transparent JSON expansion.
=> Expand json

README.md, containers/general/tool.go, sophos/client.go
=> sophos adapter, first pass

containers/general/tool.go, okta/client.go
=> adding okta logs integration

okta/client.go
removing dupe events -- using the last event timestamp received as the timestamp for the next call results in returning the last event as a duplicate. checking for dupes and removing from results.
=> removing dupe events

mac_unified_logging/client.go, mac_unified_logging/conf.go, mac_unified_logging/log.go
=> adding predicate option 

cloudbuild_release.yaml, containers/zeek_extract/Dockerfile, containers/zeek_extract/README.md, containers/zeek_extract/run.sh, containers/zeek_extract/upload_file.sh, containers/zeek_extract/upload_new_files.sh
Added a new container definition similar to the Zeek one we had. This one will run Zeek in the container, send the telemetry to LC via an Adapter, AND it will extract all files from the stream and upload them as an Artifact to LC.
=> Draft of a zeek container also extracting and uploading to LC.

cato/client.go, containers/general/tool.go, go.mod
cato events feed api adapter, tested and working in my demo env
=> cato events feed api adapter

containers/general/Dockerfile
Need to update the golang container.
=> Update build container.

containers/general/tool.go, entraid/client.go
entra id detections via api, first pass
=> entra id detections via api, first pass

cato/client.go
fix rate limiting for cato api
=> fix rate limiting for cato api

cato/client.go
=> retry upon api error to fix stopping adapter when api errors out

go.mod, go.sum
=> grpc update for vanta

defender/client.go
add retries and fix verbiage to alleviate confusion about errors coming back from the API (not our side)
=> add retries and fix verbiage

entraid/client.go
making same changes for entra id as i made for defender re:retries and verbiage
=> making same changes for entra id as i made for defender re:retries and verbiage

imap/client.go
Remove code differentiating attachment from not attachment as it was causing parsing issues.
=> Remove some code diff for attachment.

README.md, containers/general/tool.go, containers/general/win_service.go, file/client.go
- Support for multiple JSON/YAML documents in a single config file to run multiple adapter instances within the single adapter process.
- Support for file globbing in the `file` adapter type to collect from dynamic sets of files: https://pkg.go.dev/path/filepath#Match
=> Multi tail

containers/general/tool.go
Regression introduced in the CLI parsing.
=> Fix CLI parsing.

entraid/client.go
Report auth errors by themselves.
=> Enhance entra-id errors.

okta/client.go
Refactor to pull from last 30 minutes while deduping events already reported. This is because the Okta API apparently can report older events up to several hours late. We won't go that far in time because of the memory overhead, we'll see how prevalent this is.
=> Tweak Okta adapter to deal with very delayed messages.

o365/client.go
- We were reading the body twice by mistake.
- If the MS API does not return JSON, we will also return the raw response.
=> Fix error when o365 has no json.

go.mod, go.sum
=> Update USP client with JSON fix.

go.mod, go.sum
> Description here
Fix refractionPOINT/tracking#1
=> removing indirect opentelem module and updating grpc lib

cato/client.go
updating marker to fix gaps in data
=> updating marker to fix gaps in data

containers/general/tool.go, zendesk/client.go
=> adding zendesk adapter

containers/general/tool.go, pandadoc/client.go
=> adding pandadoc adapter

containers/general/tool.go, mimecast/client.go
=> adding mimecast

sentinelone/s1.go
Was parsing out not quite the right event_type.
=> Fix event type

containers/conf/all.go, containers/general/tool.go, sublime/client.go
adding sublime security audit api adapter
=> adding sublime security audit api adapter

containers/conf/all.go, containers/general/tool.go
=> Fix the file parsing.

falconcloud/client.go
Changing the handling of the falconcloud stream to drop all pre-Now() events on every boot.
This is very sub-par but it's all Crowdstrike decided to give out.
=> Handle live collection from falconcloud and support offsets.

containers/conf/all.go, containers/general/tool.go, proofpoint_tap/client.go
> Adapter addition for pulling Proofpoint Tap logs
BHISSOC/tracking#86
=> Proofpoint Adapter

wiz/client.go
> Updates to the Wiz adapter after testing
BHISSOC/tracking#44
=> Testing Updates
